[package]
name = "futures-concurrency"
version = "2.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yoshuawuyts/futures-concurrency"
documentation = "https://docs.rs/futures-concurrency"
description = "Concurrency extensions for Future"
readme = "README.md"
edition = "2018"
keywords = []
categories = []
authors = [
    "Yoshua Wuyts <yoshuawuyts@gmail.com>"
]

[features]

[dependencies]
futures-core = "0.3.16"
pin-project = "1.0.8"
thread_local = "1.1.3"
async-trait = "0.1.52"

[dev-dependencies]
futures-lite = "1.12.0"
futures = "0.3.19"
